### ISSUE TITLE
BUG - font-size

### ISSUE THREAD

**Issue by ChristineZwaan** [ESI-FAR/INA-tool#82] opened 2024-07-29 11:27 UTC
When downloading the PNG file, the font-size in relation to the size of the boxes is really small. It is not quite readable yet. Would it be an option to either make the boxes smaller or the font-size larger

![image](https://github.com/user-attachments/assets/58d9517e-61e4-41ba-a488-f62dd5b9de78)

**Comment by sjvrijn** [comment] 2024-08-05 10:54
Marking this as a duplicate of #71 (work in progress)

**Closed by sjvrijn** 2024-08-05 10:54 UTC
Labels: bug, duplicate
